### ISSUE TITLE
Cannot Build / Install

### ISSUE THREAD

**Issue by vanvanni** [felixrieseberg/razer-chroma#8]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'razer-chroma' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session b5ef9617c8726be5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/razer-chroma 140ms (from cache)
8 silly pacote tag manifest for razer-chroma@latest fetched in 151ms
9 timing stage:loadCurrentTree Completed in 163ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule razer-chroma@0.2.4 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/bindings 47ms (from cache)
18 silly pacote range manifest for bindings@^1.2.1 fetched in 48ms
19 silly resolveWithNewModule bindings@1.5.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 34ms (from cache)
21 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 36ms
22 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
23 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 90ms
24 timing stage:loadIdealTree Completed in 91ms
25 silly currentTree test
26 silly idealTree test
26 silly idealTree +-- bindings@1.5.0
26 silly idealTree +-- file-uri-to-path@1.0.0
26 silly idealTree `-- razer-chroma@0.2.4
27 silly install generateActionsToTake
28 timing stage:generateActionsToTake Completed in 3ms
29 silly diffTrees action count 3
30 silly diffTrees add file-uri-to-path@1.0.0
31 silly diffTrees add bindings@1.5.0
32 silly diffTrees add razer-chroma@0.2.4
33 silly decomposeActions action count 24
34 silly decomposeActions fetch file-uri-to-path@1.0.0
35 silly decomposeActions extract file-uri-to-path@1.0.0
36 silly decomposeActions preinstall file-uri-to-path@1.0.0
37 silly decomposeActions build file-uri-to-path@1.0.0
38 silly decomposeActions install file-uri-to-path@1.0.0
39 silly decomposeActions postinstall file-uri-to-path@1.0.0
40 silly decomposeActions finalize file-uri-to-path@1.0.0
41 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
42 silly decomposeActions fetch bindings@1.5.0
43 silly decomposeActions extract bindings@1.5.0
44 silly decomposeActions preinstall bindings@1.5.0
45 silly decomposeActions build bindings@1.5.0
46 silly decomposeActions install bindings@1.5.0
47 silly decomposeActions postinstall bindings@1.5.0
48 silly decomposeActions finalize bindings@1.5.0
49 silly decomposeActions refresh-package-json bindings@1.5.0
50 silly decomposeActions fetch razer-chroma@0.2.4
51 silly decomposeActions extract razer-chroma@0.2.4
52 silly decomposeActions preinstall razer-chroma@0.2.4
53 silly decomposeActions build razer-chroma@0.2.4
54 silly decomposeActions install razer-chroma@0.2.4
55 silly decomposeActions postinstall razer-chroma@0.2.4
56 silly decomposeActions finalize razer-chroma@0.2.4
57 silly decomposeActions refresh-package-json razer-chroma@0.2.4
58 silly install executeActions
59 silly doSerial global-install 24
60 verbose correctMkdir C:\Users\XJoeyV\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
61 verbose lock using C:\Users\XJoeyV\AppData\Roaming\npm-cache\_locks\staging-8fb0e99b64fdb046.lock for C:\Users\XJoeyV\Desktop\test\node_modules\.staging
62 silly doParallel extract 3
63 silly extract file-uri-to-path@1.0.0
64 silly extract bindings@1.5.0
65 silly extract razer-chroma@0.2.4
66 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
67 silly tarball trying bindings@^1.2.1 by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
68 silly tarball trying razer-chroma@latest by hash: sha1-TqDVvTP5iVlgZvsRLmIkODXFg0Q=
69 silly extract bindings@^1.2.1 extracted to C:\Users\XJoeyV\Desktop\test\node_modules\.staging\bindings-b1a86777 (19ms)
70 silly extract file-uri-to-path@1.0.0 extracted to C:\Users\XJoeyV\Desktop\test\node_modules\.staging\file-uri-to-path-2cfb19b1 (22ms)
71 silly extract razer-chroma@latest extracted to C:\Users\XJoeyV\Desktop\test\node_modules\.staging\razer-chroma-4b429777 (23ms)
72 timing action:extract Completed in 26ms
73 silly doReverseSerial unbuild 24
74 silly doSerial remove 24
75 silly doSerial move 24
76 silly doSerial finalize 24
77 silly finalize C:\Users\XJoeyV\Desktop\test\node_modules\file-uri-to-path
78 silly finalize C:\Users\XJoeyV\Desktop\test\node_modules\bindings
79 silly finalize C:\Users\XJoeyV\Desktop\test\node_modules\razer-chroma
80 timing action:finalize Completed in 6ms
81 silly doParallel refresh-package-json 3
82 silly refresh-package-json C:\Users\XJoeyV\Desktop\test\node_modules\file-uri-to-path
83 silly refresh-package-json C:\Users\XJoeyV\Desktop\test\node_modules\bindings
84 silly refresh-package-json C:\Users\XJoeyV\Desktop\test\node_modules\razer-chroma
85 timing action:refresh-package-json Completed in 15ms
86 silly doParallel preinstall 3
87 silly preinstall file-uri-to-path@1.0.0
88 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
89 silly preinstall bindings@1.5.0
90 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
91 silly preinstall razer-chroma@0.2.4
92 info lifecycle razer-chroma@0.2.4~preinstall: razer-chroma@0.2.4
93 timing action:preinstall Completed in 1ms
94 silly doSerial build 24
95 silly build file-uri-to-path@1.0.0
96 info linkStuff file-uri-to-path@1.0.0
97 silly linkStuff file-uri-to-path@1.0.0 has C:\Users\XJoeyV\Desktop\test\node_modules as its parent node_modules
98 silly build bindings@1.5.0
99 info linkStuff bindings@1.5.0
100 silly linkStuff bindings@1.5.0 has C:\Users\XJoeyV\Desktop\test\node_modules as its parent node_modules
101 silly build razer-chroma@0.2.4
102 info linkStuff razer-chroma@0.2.4
103 silly linkStuff razer-chroma@0.2.4 has C:\Users\XJoeyV\Desktop\test\node_modules as its parent node_modules
104 timing action:build Completed in 1ms
105 silly doSerial global-link 24
106 silly doParallel update-linked 0
107 silly doSerial install 24
108 silly install file-uri-to-path@1.0.0
109 info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
110 silly install bindings@1.5.0
111 info lifecycle bindings@1.5.0~install: bindings@1.5.0
112 silly install razer-chroma@0.2.4
113 info lifecycle razer-chroma@0.2.4~install: razer-chroma@0.2.4
114 verbose lifecycle razer-chroma@0.2.4~install: unsafe-perm in lifecycle true
115 verbose lifecycle razer-chroma@0.2.4~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\XJoeyV\Desktop\test\node_modules\razer-chroma\node_modules\.bin;C:\Users\XJoeyV\Desktop\test\node_modules\.bin;C:\Users\XJoeyV\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\XJoeyV\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs;C:\Program Files (x86)\sox-14-4-2;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet;C:\Users\XJoeyV\.windows-build-tools\python27;C:\Users\XJoeyV\AppData\Local\Microsoft\WindowsApps;C:\Users\XJoeyV\AppData\Local\GitHubDesktop\bin;C:\Users\XJoeyV\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\XJoeyV\AppData\Roaming\npm;C:\Users\XJoeyV\AppData\Local\Programs\Fiddler;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
116 verbose lifecycle razer-chroma@0.2.4~install: CWD: C:\Users\XJoeyV\Desktop\test\node_modules\razer-chroma
117 silly lifecycle razer-chroma@0.2.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
118 silly lifecycle razer-chroma@0.2.4~install: Returned: code: 1  signal: null
119 info lifecycle razer-chroma@0.2.4~install: Failed to exec install script
120 timing action:install Completed in 531ms
121 verbose unlock done using C:\Users\XJoeyV\AppData\Roaming\npm-cache\_locks\staging-8fb0e99b64fdb046.lock for C:\Users\XJoeyV\Desktop\test\node_modules\.staging
122 timing stage:rollbackFailedOptional Completed in 7ms
123 timing stage:runTopLevelLifecycles Completed in 855ms
124 silly saveTree test
124 silly saveTree `-- razer-chroma@0.2.4
124 silly saveTree   `-- bindings@1.5.0
124 silly saveTree     `-- file-uri-to-path@1.0.0
125 warn enoent ENOENT: no such file or directory, open 'C:\Users\XJoeyV\Desktop\test\package.json'
126 verbose enoent This is related to npm not being able to find a file.
127 warn test No description
128 warn test No repository field.
129 warn test No README data
130 warn test No license field.
131 verbose stack Error: razer-chroma@0.2.4 install: `node-gyp rebuild`
131 verbose stack Exit status 1
131 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
131 verbose stack     at EventEmitter.emit (events.js:198:13)
131 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
131 verbose stack     at ChildProcess.emit (events.js:198:13)
131 verbose stack     at maybeClose (internal/child_process.js:982:16)
131 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
132 verbose pkgid razer-chroma@0.2.4
133 verbose cwd C:\Users\XJoeyV\Desktop\test
134 verbose Windows_NT 10.0.18362
135 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "razer-chroma"
136 verbose node v10.16.0
137 verbose npm  v6.9.0
138 error code ELIFECYCLE
139 error errno 1
140 error razer-chroma@0.2.4 install: `node-gyp rebuild`
140 error Exit status 1
141 error Failed at the razer-chroma@0.2.4 install script.
141 error This is probably not a problem with npm. There is likely additional logging output above.
142 verbose exit [ 1, true ]
```

**Comment by NoodleBug** [comment]
Looks like the project has been abandoned
